BaiTap3_61133538/BaiTap3_61133538/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap3_61133538.Models
{
    public class EmpModel
    {
        public string EmpID { get; set; }
        public string Name { get; set; }
        public DateTime BirthOfDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string Avatar { get; set; }
    }
}

BaiTap3_61133538/BaiTap3_61133538/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap3_61133538.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BaiTap3_61133538/BaiTap3_61133538/Controllers/Nhanvien_61133538Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaiTap3_61133538.Models;

namespace BaiTap3_61133538.Controllers
{
    public class Nhanvien_61133538Controller : Controller
    {
        // GET: Nhanvien_61133538
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Detaill()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Detaill(HttpPostedFileBase Avatar, EmpModel emp)
        {
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            Avatar.SaveAs(path);
            string fSave = Server.MapPath("/emp.txt");
            string[] emInfo =
            {emp.EmpID, emp.Name, emp.BirthOfDate.ToShortDateString(),
                emp.Email,emp.Password,emp.Department, postedFileName};
            //Lưu các thông ti vào tập tin emp.txt
            System.IO.File.WriteAllLines(fSave, emInfo);
            //Ghi nhận các thông tin đăng ký để hiện thị trên View Confirm
            ViewBag.EmpID = emInfo[0];
            ViewBag.Name = emInfo[1];
            ViewBag.BirthOfDate = emInfo[2].ToString();
            ViewBag.Email = emInfo[3];
            ViewBag.Password = emInfo[4];
            ViewBag.Department = emInfo[5];
            ViewBag.Avatar = "/Images/" + emInfo[6];
            return View("Confirm");
        }
        public ActionResult Confirm(EmpModel emp)
        {
            return View();
        }
    }
}

BaiTap3_61133538/BaiTap3_61133538/Views/Nhanvien_61133538/Confirm.cshtml
@{
    ViewBag.Title = "Comfirm";
    Layout = null;
}

<h2>THÔNG TIN THÀNH VIÊN ĐÃ ĐĂNG KÝ</h2>
<ul>
    <li>MÃ NHÂN VIÊN : @ViewBag.EmpID</li>
    <li>HỌ TÊN : @ViewData["Name"]</li>
    <li>ngày sinh: @ViewBag.BirthOfDate</li>
    <li>Email : @ViewData["Email"]</li>
    <li>Mật khẩu : @ViewBag.Password</li>
    <li>Phòng ban : @ViewBag.Department</li>
    <li>Ảnh đại diện : @ViewData["Avatar"]</li>

</ul>

BaiTap3_61133538/BaiTap3_61133538/Views/Nhanvien_61133538/Detaill.cshtml
@model BaiTap3_61133538.Models.EmpModel

@{
    ViewBag.title = "Detaill";
    Layout = null;
}


<h2>THÔNG TIN THÀNH VIÊN ĐĂNG KÝ</h2>

@{Html.BeginForm("Detaill", "Nhanvien_61133538", FormMethod.Post, new { enctype = "multipart/form-data" });}


<div>
    Mã nhân viên
</div>
<div>
    @Html.EditorFor(model => model.EmpID)
</div>

<div>
    Họ tên
</div>
<div>
    @Html.EditorFor(model => model.Name)
</div>
<div>
    Ngày sinh
</div>
<div>
    @Html.EditorFor(model => model.BirthOfDate)
</div>
<div>
    Email
</div>
<div>
    @Html.EditorFor(model => model.Email)
</div>
<div>
    Mật khẩu
</div>
<div>
    @Html.EditorFor(model => model.Password)
</div>
<div>
    Phòng ban
</div>
<div>
    @Html.EditorFor(model => model.Department)
</div>


  Ảnh đại diện
<input type="file" name="Avatar" value="chọn tệp" accept="image" required />


<div>
    <input type="submit" value="đăng ký" />

</div>


@{ Html.EndForm();}